logLevel = "DEBUG"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true

[frontends]
    [frontends.frontend1]
    backend = "client"
    priority = 10
    passHostHeader = true
      [frontends.frontend1.routes.test_1]
      rule = "Host:localhost"

[backends]
  [backends.client]
    [backends.client.maxconn]
       amount = 10
       extractorfunc = "request.host"